foreground         #c9c8c8
background         #272326
background_opacity 1.0
cursor             #c9c8c8

active_tab_foreground     #272326
active_tab_background     #c9c8c8
inactive_tab_foreground   #c9c8c8
inactive_tab_background   #272326

active_border_color   #c9c8c8
inactive_border_color #272326
bell_border_color     #A3929A

color0       #272326
color8       #7c6570
color1       #A3929A
color9       #A3929A
color2       #D1B0B5
color10      #D1B0B5
color3       #D1B4CB
color11      #D1B4CB
color4       #D8B6D9
color12      #D8B6D9
color5       #E9BACA
color13      #E9BACA
color6       #F2CED2
color14      #F2CED2
color7       #c9c8c8
color15      #c9c8c8
