[colors]
background = '#2723268e'
black = '#272326'
blue = '#A3929A'
cursor = '#c9c8c8'
cyan = '#D1B0B5'
foreground = '#c9c8c8'
green = '#D1B4CB'
magenta = '#D8B6D9'
red = '#E9BACA'
tabs = '#c9c8c8'
tabs-active = '#F2CED2'
white = '#c9c8c8'
yellow = '#c9c8c8'
dim-black = '#2723268e'
dim-blue = '#A3929A8e'
dim-cyan = '#D1B0B58e'
dim-foreground = '#c9c8c88e'
dim-green = '#D1B4CB8e'
dim-magenta = '#D8B6D98e'
dim-red = '#E9BACA8e'
dim-white = '#F2CED28e'
dim-yellow = '#c9c8c88e'
light-black = '#A3929A'
light-blue = '#D1B0B5'
light-cyan = '#D1B4CB'
light-foreground = '#D8B6D9'
light-green = '#E9BACA'
light-magenta = '#F2CED2'
light-red = '#c9c8c8'
light-white = '#A3929A'
light-yellow = '#D1B0B5'
