# pywal theme for ghostty

background = 272326
foreground = c9c8c8
cursor-color = c9c8c8
selection-background = c9c8c8
selection-foreground = 272326

palette = 0=#272326
palette = 1=#A3929A
palette = 2=#D1B0B5
palette = 3=#D1B4CB
palette = 4=#D8B6D9
palette = 5=#E9BACA
palette = 6=#F2CED2
palette = 7=#c9c8c8
palette = 8=#7c6570
palette = 9=#A3929A
palette = 10=#D1B0B5
palette = 11=#D1B4CB
palette = 12=#D8B6D9
palette = 13=#E9BACA
palette = 14=#F2CED2
palette = 15=#c9c8c8
